AllCops:
  Include:
    - Capfile
    - config.ru
    - Gemfile
    - Guardfile
    - Rakefile
    - app/views/**/*.jbuilder
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.0

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
