require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
    - node_modules/**/*
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  NewCops: enable

Rails:
  Enabled: true

#
# Coding Style
#

# 2 space indentation is preferred over aligning the dots.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Prefer `def method_name\nend` over `def method_name; end`
Style/EmptyMethod:
  EnforcedStyle: expanded

#
# Disabled Cops
#

# The puma.rb file doesn't need to have the executable bit set.
Lint/ScriptPermission:
  Exclude:
    - 'config/puma.rb'

# Rails by default ships with lines (and blocks) that are "too long".
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/*.rb'

Rails/Output:
  Exclude:
    - 'config/puma.rb'

Style/Documentation:
  Enabled: false
