require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
    - node_modules/**/*
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  NewCops: enable

Rails:
  Enabled: true

#
# Coding Style
#

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/EmptyMethod:
  EnforcedStyle: expanded

#
# Disabled Cops
#

Lint/ScriptPermission:
  Exclude:
    - 'config/puma.rb'

# Rails by default ships with lines (and blocks) that are "too long".
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/*.rb'

Rails/Output:
  Exclude:
    - 'config/puma.rb'

Style/Documentation:
  Enabled: false
