AllCops:
  Include:
    - Capfile
    - config.ru
    - Gemfile
    - Guardfile
    - Rakefile
    - app/views/**/*.jbuilder
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
