AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# False positive
Lint/UnneededSplatExpansion:
  Exclude:
    - 'app/views/**/*.jbuilder'

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
