require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
    - node_modules/**/*
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  NewCops: enable

Rails:
  Enabled: true

#
# Coding Style
#

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/EmptyMethod:
  EnforcedStyle: expanded

#
# Disabled Cops
#

# False positive
Lint/RedundantSplatExpansion:
  Exclude:
    - 'app/views/**/*.jbuilder'

# Rails by default ships with lines (and blocks) that are "too long".
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/*.rb'

Style/Documentation:
  Enabled: false

# New Cops

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
