nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONT_AWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
