default: &default
  adapter: postgresql
  encoding: unicode
  username: fustrate
  password: "not my real password"
  pool: 5

development:
  <<: *default
  dbname: baseballbot

test:
  <<: *default
  dbname: baseballbot_test
