# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ba7473f69ec13311c773b5f5666584a30d9f456cbfecbd145aeb1a711b08709b794935d565cb3b7caa33b827ac1cc609e66ab6645cf3b43a15d81426504621

test:
  secret_key_base: 297a61608547a49918af3059ab51d9f9243eb841d1b9f74858f2990907e9aca944ccccb56d8c7b11d1f45ee3288aaa52876364ecf90c7a0a4085aa406e57747d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
